### ISSUE TITLE
ActionSheetViewDelegate not calling implemented stubs

### ISSUE THREAD

**Issue by farrukhaskari1** [josechagas/ActionSheetView#1]
self.delegate adding stubs but not calling them on navigation viewController

**Comment by farrukhaskari1** [comment]
self.containerView.frame.size.height is empty (nil value)

**Comment by josechagas** [comment]
Hey askari01 after reading your messages I reviewed the project and I am not sure if I found a solution, so I have some possibilities.

1 - Probably you are forgetting to inform the segue identifier to your class that inherits from ASManagerVC. I think this is not the case because without the identifier your ActionSheetView does not appear.

2 - Take a look if you are removing the childViewControllers from your class that inherits from ASManagerVC.

If any of these options are not the solution please give me a better explanation about the situation for I try to reproduce here, for example what are the source and destination UIViewControllers of ASViewSegue segue.

I am sorry for not answering faster.

**Comment by josechagas** [comment]
3 - Your destination UIViewController class of ASViewSegue segue now really needs to implement ActionSheetView protocol.

If this is the problem I will fix README file because its not so clear.

**Comment by farrukhaskari1** [comment]
the view is rootViewController 
segue is implemented
not removing AsManagerVC class
actionSheetView protocols are implemented
but still not working.

**Comment by farrukhaskari1** [comment]
ActionSheetViewDelegate func are not being called

**Comment by josechagas** [comment]
"the view is rootViewController", so your segue points to a UINavigationController ?!
If this is true your UINavigationController needs to implement ActionSheetView

**Comment by farrukhaskari1** [comment]
it is implementing ActionSheetView, is it possible that u look at my code ?

**Comment by josechagas** [comment]
make RatingTestVC implement ActionSheetView protocol and test.

**Comment by farrukhaskari1** [comment]
**Navigation:**
<img width="863" alt="screen shot 2018-02-17 at 12 10 16 am" src="https://user-images.githubusercontent.com/6830947/36324879-b24052b4-1377-11e8-8012-8872c07306a5.png">

**Action Sheet View**
<img width="1280" alt="screen shot 2018-02-17 at 12 12 36 am" src="https://user-images.githubusercontent.com/6830947/36324884-b399fd36-1377-11e8-8a0f-7e928939be36.png">

**ASManager and Delegate**
<img width="978" alt="screen shot 2018-02-17 at 12 15 03 am" src="https://user-images.githubusercontent.com/6830947/36324885-b7061dd8-1377-11e8-874b-905b6fd6c59d.png">

**Segue**
<img width="1280" alt="screen shot 2018-02-17 at 12 19 53 am" src="https://user-images.githubusercontent.com/6830947/36325067-51f9c57e-1378-11e8-9199-b8035f6d2f47.png">

**Comment by josechagas** [comment]
Are you overriding viewWillAppear method on your class that inherit ASManagerVC ?
If yes call super.viewWillAppear inside of it.

**Comment by josechagas** [comment]
Looking for the images it seems to be everything ok.

**Comment by askari01** [comment]
<img width="1086" alt="screen shot 2018-02-17 at 12 24 48 am" src="https://user-images.githubusercontent.com/6830947/36325244-00e07b64-1379-11e8-9db2-0a018f2ae998.png">
yes i am overriding it

**Comment by josechagas** [comment]
is it of your class WaitingVC or from my class ASManagerVC ? 
If its from your class, you do not need to call the methods performSegue and tryToAddDarkLayer for it works

**Comment by farrukhaskari1** [comment]
calling super.viewWillAppear solved it for me, how silly of me. if you allow can I close and comment

**Comment by josechagas** [comment]
I am really happy it worked and I am sorry because my documentation was not so clear, I will fix it to avoid other problems like this.

You can close it and comment.

**Comment by farrukhaskari1** [comment]
thank you very much, for your time and help, I really like your pod. 
Have a good day mate. 

thanks
